INSERT INTO Products(Name, Description, Category, Price) VALUES
('Santa Fe Crispers Salad', 'Chicken Crispers, pico, avocado, cilantro, tortilla strips, house-made ranch & a drizzle of spicy Santa Fe sauce', 'Salads', 9.49),
('Santa Fe Chicken Salad', 'Spicy grilled chicken, pico, avocado, cilantro, tortilla strips, house-made ranch & a drizzle of spicy Santa Fe sauce.', 'Salads', 7.59),
('Quesadilla Explosion Salad', 'Grilled chicken, cheese, tomatoes, corn & black bean salsa, tortilla strips with citrus-balsamic. Served with cheese quesadillas.', 'Salads', 10.99),
('Grilled Chicken Salad', 'Tomatoes, corn & black bean salsa, shredded cheese with honey-lime vinaigrette.', 'Salads', 12.59),
('Caribbean Salad with Seared Shrimp', 'Pineapple, mandarin oranges, dried cranberries, red bell peppers, green onions, cilantro, with honey-lime dressing.', 'Salads', 11.59),
('Caribbean Salad with Grilled Chicken', 'Pineapple, mandarin oranges, dried cranberries, red bell peppers, green onions, cilantro, with honey-lime dressing.', 'Salads', 11.99),
('House Salad', 'Tomatoes, red onions, cucumbers, shredded cheese, garlic croutons with your choice of dressing.', 'Salads', 6.59),
('Boneless Buffalo Chicken Salad', 'Crispy chicken tossed in spicy Buffalo sauce, bacon, bleu cheese crumbles, pico, tortilla strips with house-made ranch.', 'Salads', 8.49),
('Bacon Avocado Grilled Chicken Sandwich', 'You definitely won"t be hungry later. Grilled chicken, bacon, provolone, avocado, sauteed onions, lettuce, tomato, cilantro-pesto mayo on a toasted buttery roll.', 'Sandwiches', 9.99),
('Buffalo Chicken Ranch Sandwich', 'Crispy chicken with spicy Buffalo sauce, tomato, lettuce, house-made ranch on a brioche bun.', 'Sandwiches', 9.49),
('California Turkey Club', 'Bacon, avocado, tomato, red onion, provolone, lettuce, cilantro-pesto mayo on wheat Texas toast.', 'Sandwiches', 8.49),
('The Boss Burger', 'The burger all other burgers report to. Smoked brisket, tender rib meat, jalapeno-cheddar smoked sausage, bacon & cheddar with lettuce, tomato, House BBQ & house-made ranch. We. Dare. You.', 'Burgers', 10.49),
('Alexs Santa Fe Burger', 'Yes, Chef Alex is real. And so are his burger skills. Stacked high with avocado, pepper Jack, red onion, roasted jalapeños, tomato, pickles, cilantro & spicy Santa Fe sauce.', 'Burgers', 10.99),
('Chilis Chili Burger', 'We brought back our 1975 Original Chili, added shredded and American cheese, sauteed onions & crispy tortilla strips.', 'Byrgers', 11.49),
('Ultimate Bacon Burger', 'Double bacon, cheddar, pickles, lettuce, red onion, tomato, jalapeño aioli, spicy Buffalo sauce, honey-chipotle sauce.', 'Burgers', 9.99),
('Sunrise Burger', 'Cage-free fried egg, provolone, bacon, lettuce, red onion, tomato, Signature sauce.', 'Burgers', 12.00),
('Southern Smokehouse Burger', 'Bacon, cheddar, pickles, Awesome Blossom Petals, lettuce, tomato, Signature sauce. Served with a side of original BBQ sauce.', 'Burgers', 11.49),
('Big Mouth Bites', '4 mini burgers with bacon, American cheese, sauteed onions, house-made ranch.', 'Burgers', 11.99),
('Guacamole Burger', 'Guacamole, provolone, jalapeños, red & green bell peppers, sauteed onions, jalapeño aioli.', 'Burgers', 10.99),
('Classic Bacon Burger', 'Cheddar, bacon, pickles, lettuce, tomato, red onion, Signature sauce.', 'Burgers', 10.49),
('Oldtimer w/Cheese', 'You can’t top burger perfection, unless you add cheese.', 'Burgers', 11.99),
('Oldtimer', 'The original burger. Pickles, lettuce, tomato, red onion, mustard.', 'Burgers', 11.99),
('Original Full Order Ribs', '', 'Ribs & Steaks', 14.49),
('Original Half Order Ribs', '', 'Ribs & Steaks', 12.99),
('Mix & Match Ribs', '', 'Ribs & Steaks', 13.49),
('House BBQ Full Order Ribs', '', 'Ribs & Steaks', 14.99),
('House BBQ Half Order Ribs', '', 'Ribs & Steaks', 12.99),
('Texas Dry Rub Full Order Ribs', '', 'Ribs & Steaks', 16.69),
('Texas Dry Rub Half Order Ribs', '', 'Ribs & Steaks', 16.49),
('Honey-Chipotle Full Order Ribs', '', 'Ribs & Steaks', 14.99),
('Honey-Chipotle Half Order Ribs', '', 'Ribs & Steaks', 14.99),
('6 oz. Classic Sirloin with Grilled Avocado', 'Seasoned & topped with spicy citrus-chile sauce, grilled avocado slices, garlic roasted tomatoes, cilantro. Served with fresco salad.', 'Ribs & Steaks', 11.99),
('Classic Sirloin - 10oz', 'Seasoned & topped with garlic butter. Served with loaded mashed potatoes, steamed broccoli.', 'Ribs & Steaks', 16.99),
('Classic Ribeye', 'Marbled, thick-cut steak topped with garlic butter. Served with loaded mashed potatoes, steamed broccoli.', 'Ribs & Steaks', 17.49),
('Classic Sirloin - 6oz', 'Seasoned & topped with garlic butter. Served with loaded mashed potatoes, steamed broccoli.', 'Ribs & Steaks', 16.49),
('SPICY TUNA TARTAR', 'Cucumber, Sesame, Soy, Wasabi, Toasted Rice, Papadum', 'Seafood', 14.00),
('SAUTEED CRAB CAKES', 'Pickled Fennel/Cherry Tomato/White Remoulade', 'Seafood', 19.00),
('LOBSTER CEVICHE', 'Orange Supreme/Avocado/Vanilla Infused Citrus Juices/Smoked Apple Wood Sea Salt', 'Seafood', 20.00),
('TRUFFLED LOBSTER MAC & CHEESE', 'Maine Lobster/Gruyere/Sea Shell Pasta/Parmesan Gratin', 'Seafood', 18.00),
('LOBSTER SPRING ROLLS', 'Soy Wilted Vegetables/Sweet Chili Dipping Sauce', 'Seafood', 16.00),
('Chilled Seafood Platter', '6 oysters, 5 prawn, 1 Crab Leg, 1 Crab Claw, 1 Lobster tail, drawn butter', 'Seafood', 75.00)